application: jenwp-195908
version: wpfromstarterproject
runtime: php
api_version: 1


handlers:
- url: /(.*\.(htm|html|css|js))$
static_files: \1
upload: .*\.(htm|html|css|js)$
application_readable: true

- url: /wp-content/(.*\.(ico|jpg|png|gif))$
static_files: wp-content/\1
upload: wp-content/.*\.(ico|jpg|png|gif)$
application_readable: true

- url: /(.*\.(ico|jpg|png|gif))$
static_files: \1
upload: .*\.(ico|jpg|png|gif)$

- url: /wp-admin/(.+)
script: wp-admin/\1
secure: always

- url: /wp-admin/
script: wp-admin/index.php
secure: always

- url: /wp-login.php
script: wp-login.php
secure: always

- url: /wp-cron.php
script: wp-cron.php
login: admin

- url: /xmlrpc.php
script: xmlrpc.php

- url: /wp-(.+).php
script: wp-\1.php

- url: /(.+)?/?
script: index.php

